### ISSUE TITLE
libspa 0.9.2 compilation error with Rust 1.94.0

### ISSUE THREAD

**Issue by qpzm7903** [qpzm7903/dailyLogger#39]
## Description

The `libspa` crate (v0.9.2), a transitive dependency through `xcap → pipewire → libspa`, fails to compile with Rust 1.94.0.

## Error

```
error[E0560]: struct `VideoFlags` has no field named `flags`
error[E0308]: mismatched types - expected `u64`, found `i64`
```

## Workaround

Use `--no-default-features` flag:
```bash
cargo build --no-default-features
cargo test --no-default-features
```

## Dependency Chain

```
daily-logger → xcap v0.9.2 → pipewire v0.9.2 → libspa v0.9.2
```

## Environment

- Rust: 1.94.0
- Platform: Linux (affects local development)
- CI: Passes (uses `--no-default-features`)

## Related

- pipewire-rs repository: https://gitlab.freedesktop.org/pipewire/pipewire-rs
